avatar/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

event/urls.py
from django.conf.urls.defaults import *
from event.views import *
from django.template import RequestContext
from django.db import models
from django.shortcuts import get_object_or_404, render_to_response
import datetime
from django.views.generic.simple import direct_to_template, redirect_to


urlpatterns = patterns('',
#    (r'^$', public_events),
    (r'^my_club_events/$', myclub_events),
    (r'^(\d+)/$', event_page),
    (r'^(\d+)/register/$', register),
    (r'^(\d+)/registered_users/$', registered_users),
    (r'^(\d+)/delete/$', delete_event),
    (r'^$', event_list),
    url(r'^$', direct_to_template, { 'template': 'events/home.html'}, name='home'),

)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from ecalife import settings, views
from django.contrib import admin
from ecalife.profiles.forms import ProfileForm
from ecalife.announcement.views import homepage
from django.contrib.auth import views as auth_views
from ecalife.search.views import search



admin.autodiscover()

urlpatterns = patterns('',
        (r'^admin/jsi18n', 'django.views.i18n.javascript_catalog'),
        (r'^admin/', include(admin.site.urls)),
        (r'^avatar/', include('avatar.urls')),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
)
urlpatterns += patterns('',
        (r'^$', auth_views.login, {'template_name': 'welcome.html'}),
        (r'^homepage/$', homepage),
        (r'^search/$', search),
#        (r'^(?P<field>\w+)/filter/$', filter),
        url(r'^profiles/edit/$', 'profiles.views.edit_profile', {'form_class': ProfileForm,}),
        (r'^profiles/', include('profiles.urls')),
    )

urlpatterns += patterns('',
        (r'^accounts/', include('registration.urls')),
        (r'^clubs/', include('club.urls')),
        (r'^announcements/', include('announcement.urls')),
        (r'^events/', include('event.urls')),
        (r'^forums/', include('forum.urls')),
        (r'^messages/', include('messages.urls')),
        (r'^calendar/',include('eventcal.urls')),
        (r'^events/(?P<yr>\d{4})/(?P<mm>\d{2})/(?P<dd>\d{2})/$','ecalife.event.views.month_listing'),
    )

##
##urlpatterns += patterns('',
##        (r'^photologue/', include('photologue.urls')),
##    )

event/models.py
from django.db import models
from announcement.models import Announcement
import django_filters
from profiles.models import StudentProfile

TIME_FIELDS = (
        ('00','00:00'),
        ('01','01:00'),
        ('02','02:00'),
        ('03','03:00'),
        ('04','04:00'),
        ('05','05:00'),
        ('06','06:00'),
        ('07','07:00'),
        ('08','08:00'),
        ('09','09:00'),
        ('10','10:00'),
        ('11','11:00'),
        ('12','12:00'),
        ('13','13:00'),
        ('14','14:00'),
        ('15','15:00'),
        ('16','16:00'),
        ('17','17:00'),
        ('18','18:00'),
        ('19','19:00'),
        ('20','20:00'),
        ('21','21:00'),
        ('22','22:00'),
        ('23','23:00'),
               )

EVENT_CATEGORY = (('', 'All Events'),
                 ('1', 'Students\' Union Events'),
                 ('2', 'Sports Events'),
                 ('3', 'Academic Club Events'),
                 ('4', 'Cultural Activity Events'),
                 ('5', 'Career Events'),
                 ('6', 'Investment & Finance Events'),
                 ('7', 'Technology-related Events'),
                 ('8', 'Skill-building Events'),
                 ('9', 'Others'),
)

class Event(Announcement):
    title = models.CharField(max_length=40)
    date = models.DateField()
    start_time = models.CharField(max_length=2, choices=TIME_FIELDS)
    end_time = models.CharField(max_length=2, choices=TIME_FIELDS)
    venue = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/', blank=True)
    registered = models.ManyToManyField(StudentProfile, blank=True)
    category = models.CharField(max_length=2, choices=EVENT_CATEGORY)
#    registration_link = models.URLField(verify_exists=True, blank=True)

    def __init__(self, *args, **kwargs):
        super(Event, self).__init__(*args, **kwargs)

    def __unicode__(self):
        return self.club + ' : ' + self.title
##        return self.club + " : " + self.title


class EventFilter(django_filters.FilterSet):
    date = django_filters.DateFilter(lookup_type='lt')
    class Meta:
        model = Event
        fields = ['category', 'date']

#    def __init__(self, *args, **kwargs):
#        super(EventFilter, self).__init__(*args, **kwargs)
#        self.filters['category'].extra.update(
#            {'empty_label': u'All Categories'})

##def month_listing(request,yr,mm,dd):
##    yr1=int(yr)
##    mm1=int(mm)
##    dd1=int(dd)
##    eventdetail=Event.objects.filter(date=datetime.date(yr1,mm1,dd1))
##    return render_to_response('events/calendar.html',{'eventdetail':eventdetail},context_instance=RequestContext(request))
    

event/forms.py
from django import forms
from event.models import Event
from settings import DATE_INPUT_FORMATS
from django.contrib.admin import widgets

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ['club', 'date_posted', 'image', 'registered']

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
#        self.fields['date'].widget = widgets.AdminDateWidget()
        self.fields['date'].initial = 'yyyy-dd-mm'
        self.fields.keyOrder = ['title','announcement', 'category','date','start_time','end_time','venue','viewership']

    def clean(self):
        
        return self.cleaned_data

event/views.py
from datetime import datetime
from itertools import chain
from operator import attrgetter
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from event.forms import EventForm
from event.models import Event, EventFilter
from club.models import Member, Club
from announcement.models import Announcement
from profiles.models import StudentProfile
import datetime


def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items


@login_required
def add_event(request, pk):
    club = Club.objects.get(pk=pk)
    if request.POST:
        event = Event(club=club)
        form = EventForm(request.POST,instance=event )
        if form.is_valid():
            event = form.save()
            event.save()
            return render_to_response('event/successful_post.html', context_instance = RequestContext(request))

    else:
        form = EventForm()

    return render_to_response('club/add_event.html', {'form':form}, context_instance = RequestContext(request))


def event_page(request, pk):
    event = Event.objects.get(pk=pk)
    already_registered = False
    is_admin = False

    if request.user.is_authenticated():
        student = StudentProfile.objects.get(user=request.user)
        if student in event.registered.all():
            already_registered = True
        club = event.club
        if Member.objects.filter(club=club, student__user=request.user, admin=True):
            is_admin = True
    return render_to_response('event/event_page.html', {'event':event, 'is_admin':is_admin, 'already_registered':already_registered}, context_instance = RequestContext(request))


@login_required
def register(request, pk): # registering for an event
    event = Event.objects.get(pk=pk)
    already_there = False
    student = StudentProfile.objects.get(user=request.user)
    if student in event.registered.all():
        already_there = True
    if not already_there:
        event.registered.add(student)
        event.save()
    return render_to_response('event/successful_registration.html',{'already_there':already_there, 'event':event}, context_instance=RequestContext(request))


## used for showing with the calendar
@login_required
def registered_events(request):
    events = []
    for event in Event.objects.all():
        if request.user in event.registered.all:
            events.append(event)
    return render_to_response('event/registered.html',{'events':events}, context_instance=RequestContext(request))


#deprecated
@login_required
def myclub_events(request):
    events = []
    student = StudentProfile.objects.get(user = request.user)
    for club in Club.objects.all():
        if student in club.members.all():
            event = Event.objects.filter(club = club)
            events.extend(event)

    events.sort(key=attrgetter('date'), reverse=False)
    events = mk_paginator(request, events, 6)
    return render_to_response('event/myclub.html',{'events':events}, context_instance=RequestContext(request))


def all_events(request):
    events = []
    if request.user.is_authenticated():
        student = StudentProfile.objects.get(user = request.user)
    for club in Club.objects.all():
        for event in Event.objects.filter(club=club).filter(date__gte = datetime.datetime.now()):
##        for event in Event.objects.filter(club=club).filter(date__gte = datetime.now()):
            if event.viewership == 'P':
                events.append(event)
            if request.user.is_authenticated():
                if event.viewership == 'S':
                    events.append(event)
                if event.viewership == 'M' and (student in club.members.all()):
                    events.append(event)
    return events



def public_events(request):
    events = all_events(request)
    events.sort(key=attrgetter('date'), reverse=False)
    events = mk_paginator(request, events, 6)
    return render_to_response('event/allclubs.html',{'events':events}, context_instance=RequestContext(request))


@login_required
def registered_users(request, pk):
    event = Event.objects.get(pk=pk)
    students = event.registered.all()
    return render_to_response('event/registered_users.html',{'students':students, 'event':event}, context_instance=RequestContext(request))


def club_wise_events(request, pk):
    club = Club.objects.get(pk=pk)
    events = Event.objects.filter(club=club)
    events = mk_paginator(request, events, 6)
    return render_to_response('club/club_wise_events.html',{'events':events},context_instance=RequestContext(request))


def delete_event(request, pk):
    event = Event.objects.get(pk=pk)
    event.delete()
    return render_to_response('event/event_deleted.html', context_instance=RequestContext(request))


# filtering events
def event_list(request):
    student = []
    events = []
    f = EventFilter(request.GET, queryset=Event.objects.all())
    if request.user.is_authenticated():
        student = StudentProfile.objects.get(user = request.user)

    event = Event.objects.filter(date__lt = datetime.datetime.now())
    event.delete()

    for event in f:
        events.append(event)

    events.sort(key=attrgetter('date'))
    events = mk_paginator(request, events, 6)
    return render_to_response('event/filter.html', {'filter':f, 'student':student, 'events':events}, context_instance=RequestContext(request))


def calendar_landing_page(request):
    now=datetime.datetime.now()
    year =  now.year
    month= now.month
    day= now.day
    return month_listing(request,year,month,day)

    
    

def month_listing(request,yr,mm,dd):
    yr1=int(yr)
    mm1=int(mm)
    dd1=int(dd)
    event= all_events(request)
    eventdetail=Event.objects.filter(date=datetime.date(yr1,mm1,dd1))
    events = []
    for i in eventdetail:
        for j in event:
            if i == j:
                events.append(j)
    
    has_event=False

    if events:
        has_event=True
            

            
    return render_to_response('events/calendar.html',{'eventdetail':events,'has_event':has_event},context_instance=RequestContext(request))

templates/event/allclubs.html
{% extends 'event/base.html' %}

{% block content %}

     <div><a href="/events/" class=button> All Events</a> &nbsp; &nbsp;<a href="/events/filter/" class=button>Filter Events</a></div>
	 <div style="height:5px;"></div><hr>

    {% block event_list %}

	<div id = "pagetitle-24">All Events</div><!--End of pagetitle-24-->

    {% if events %}
        {% for event in events.object_list %}
        <div id = "trueannouncement-23" class = "shadowin">
            <a href="/events/{{ event.pk }}/">{{ event.title }}</a><br>
            {{ event.date }} : {{ event.announcement|truncatewords_html:"50"|safe  }}<br>
            Meant for: {{ event.get_viewership_display }}
        </div><!--End of trueannouncement-23-->
        {% endfor %}

       {% else %}
       <div id = "falseannouncement-23" class = "shadowin">
        No Events available!
       </div><!--End of falseannouncement-23-->

    {% endif %}

      {% if events.object_list and events.paginator.num_pages > 1 %}
				<div class="pagination">
				    <span class="step-links">
				        {% if events.has_previous %}
				            <a href= "?page={{ events.previous_page_number }}">&nbsp;&nbsp;Previous</a>
				        {% endif %}

						{% if events.has_next %}
				            <a href="?page={{ events.next_page_number }}">&nbsp;&nbsp;Next</a>
				        {% endif %}

				  		<span class="current">
				   			&nbsp;(Page {{ events.number }} of {{ events.paginator.num_pages }})
				    	</span>
					</span>
				</div>
{% endif %}

    {% endblock %}

{% endblock %}

templates/event/base.html
{% extends 'site_base.html' %}

{% block title %}
    Event
{% endblock %}

{% block content %}

{% endblock %}

templates/event/event_deleted.html
{% extends 'event/base.html' %}

{% block content %}

    <p>The event has been successfully deleted!</p>

{% endblock %}

templates/event/event_page.html
{% extends 'event/base.html' %}

{% block content %}

   	<div id="event_details">

		<div id = "pagetitle-24">
      	{{ event.title }}
      	</div><!--End of pagetitle-24-->

	<div id="neutralannouncement-23" class="shadowin">

       	{% if already_registered %}

      	<font color="green"><b>You have registered for this event.</b></font><br><br>
      	{% else %}

      	<a id="register_button" href="/events/{{ event.pk }}/register">Register for event</a><br><br>
        {% endif %}




        Date Posted: {{ event.date_posted }}<br>
		Description: {{ event.announcement|safe }}<br><br>
		<b style="font-size:1.2em">Event Information</b><br>
        Event Date: {{ event.date }}<br>
        Time: {{ event.get_start_time_display}} - {{ event.get_end_time_display }}<br>
        Venue: <span onclick="eventMap('{{ event.venue }}');" onmouseover="this.style.cursor='pointer';"><a href="#">{{ event.venue }}</a></span><br>
        Meant for: {{ event.get_viewership_display }}
		<div id = "mapArea"></div>
        <!--<span id="float_right/left"><img src={{ MEDIA_ROOT }}{{ event.image }}/></span></p>-->

    </div>



    {% if is_admin %}
		<div id = "neutralannouncement-23" class = "shadowin">
		You are an administrator of this club.
        <div id="student_registered"><a href="/events/{{ event.pk }}/registered_users/">Click here to view the list of Students Registered</a></div>
		</div>
        <br>
        <br>
			<div id="outer{{ event.pk }}" onclick="eventDelete({{ event.pk }});"><a href="#" class = 'button'>Delete this event</a>
			<div id="inner{{ event.pk }}" class="confirmation">
			<p>Are you sure you want to delete this event?</p>
			<p><a href="/events/{{ event.pk }}/delete/">Yes</a></p>
			<p><a href="#">No</a></p>
			</div>
			</div>

    {% endif %}
    </div><!--End of announcement-23-->

{% endblock %}

templates/event/filter.html
 {% extends 'event/base.html' %}

{% block content %}

     <div><a href="/events/" class=button> All Events</a> &nbsp; &nbsp;<a href="/events/my_club_events/" class=button>My Club Events</a></div>
	 <div style="height:5px;"></div><hr>

    {% block event_list %}
        <p>Select a category and press "submit" to view events by category. You can also filter events from now to date entered.</p>
        <form action="" method="get">
            {{ filter.form.as_p }}
            <input type="submit" class = "button" style = 'font-weight: bold;'/>
        </form>
        <script>
		pickDate();
		</script>
        {% if events.object_list %}
            {% for event in events.object_list %}
                {% if event.viewership == 'P' %}
                    <div id = "trueannouncement-23" class = "shadowin">
                    <a href="/events/{{ event.pk }}/">{{ event.title }}</a><br>
                    {{ event.date }} : {{ event.announcement|truncatewords_html:"50"|safe  }}<br>
                    Meant for: {{ event.get_viewership_display }}
                    </div>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if event.viewership == 'S' %}
                    <div id = "trueannouncement-23" class = "shadowin">
                    <a href="/events/{{ event.pk }}/">{{ event.title }}</a><br>
                    {{ event.date }} : {{ event.announcement|truncatewords_html:"50"|safe  }}<br>
                    Meant for: {{ event.get_viewership_display }}
                    </div>
                    {% endif %}
                    {% if event.viewership == 'M' %}
                        {% if student in event.club.members.all %}
                            <div id = "trueannouncement-23" class = "shadowin">
                            <a href="/events/{{ event.pk }}/">{{ event.title }}</a><br>
                            {{ event.date }} : {{ event.announcement|truncatewords_html:"50"|safe  }}<br>
                            Meant for: {{ event.get_viewership_display }}
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% else %}
            <div id="falseannouncement-23" class = "shadowin">No results found!</div>
        {% endif %}

          {% if events.object_list and events.paginator.num_pages > 1 %}
					<div class="pagination">
					    <span class="step-links">
					        {% if events.has_previous %}
					            <a href= "?page={{ events.previous_page_number }}">&nbsp;&nbsp;Previous</a>
					        {% endif %}

							{% if events.has_next %}
					            <a href="?page={{ events.next_page_number }}">&nbsp;&nbsp;Next</a>
					        {% endif %}

					  		<span class="current">
					   			&nbsp;(Page {{ events.number }} of {{ events.paginator.num_pages }})
					    	</span>
						</span>
					</div>
{% endif %}

    {% endblock %}

{% endblock %}

templates/event/myclub.html
{% extends 'event/filter.html' %}

{% block event_list %}

	<div id = "pagetitle-24">My Club Events</div><!--End of pagetitle-24-->

    {% if events %}
        {% for event in events.object_list %}
            <div id = "trueannouncement-23" class = "shadowin">
            <a href="/events/{{ event.pk }}/">{{ event.title }}</a><br>
            {{ event.date }} : {{ event.announcement|safe }}<br>
            Meant for: {{ event.get_viewership_display }}
            </div><!--End of trueannouncement-23-->
        {% endfor %}

        {% else %}
		<div id = "falseannouncement-23" class = "shadowin">
        No club events available!
        </div><!--End of falseannouncement-23-->

    {% endif %}

      {% if events.object_list and events.paginator.num_pages > 1 %}
				<div class="pagination">
				    <span class="step-links">
				        {% if events.has_previous %}
				            <a href= "?page={{ events.previous_page_number }}">&nbsp;&nbsp;Previous</a>
				        {% endif %}

						{% if events.has_next %}
				            <a href="?page={{ events.next_page_number }}">&nbsp;&nbsp;Next</a>
				        {% endif %}

				  		<span class="current">
				   			&nbsp;(Page {{ events.number }} of {{ events.paginator.num_pages }})
				    	</span>
					</span>
				</div>
{% endif %}

{% endblock %}

templates/event/registered_users.html
{% extends 'event/base.html' %}

{% block content %}

<p>Registered students for {{ event.title }}</p>

<div id="list_users_registered">
<ul>
<table border =1 width = 80%>
<tr><td width = 40% style = 'padding : 3px;'>Name</td><td width = 60% style = 'padding : 3px;'>Email</td></tr>
{% for student in students %}

    <li><tr><td>{{ student.user.first_name }} {{ student.user.last_name }} </td><td>{{student.user.email}} </td></tr> </li>
{% endfor %}
</table>
</ul>
</div>

    <div id="backToEventPage"><a href="/events/{{ event.pk }}/" class = 'button'>Back to Event Page</a></div>

{% endblock %}

templates/event/successful_post.html
{% extends 'event/base.html' %}

{% block content %}

	<div id="pagetitle-24">Success!</div>
    <div id="neutralannouncement-23" class="shadowin">Your club event has been successfully posted!</div>

{% endblock %}

templates/event/successful_registration.html
{% extends 'event/base.html' %}

{% block content %}

    {% if already_there %}
<div id="pagetitle-24">Registered!</div>
        <div id="neutralannouncement-23" class="shadowin">You have already been registered for this event.</div>
    <div id="back_link"><a href="/events/{{ event.pk }}/"class = "button">Back to Event Page</a></div>
    {% else %}
<div id="pagetitle-24">Success!</div>
        <div id="neutralannouncement-23" class="shadowin">Thank You for registering. See you at the event.</div>
    <div id="back_link"><a href="/events/{{ event.pk }}/"class = "button">Back to Event Page</a></div>

    {% endif %}



{% endblock %}